#!/bin/bash --norc

PATH="external/org_linaro_components_toolchain_gcc_armv7/libexec/gcc/arm-linux-gnueabi/5.5.0:$PATH" \
    exec \
    external/org_linaro_components_toolchain_gcc_armv7/bin/arm-linux-gnueabi-gcc \
    "$@"
