// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: src/main/proto/wxhomework.proto
#ifndef GRPC_src_2fmain_2fproto_2fwxhomework_2eproto__INCLUDED
#define GRPC_src_2fmain_2fproto_2fwxhomework_2eproto__INCLUDED

#include "src/main/proto/wxhomework.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace wxhomework {

class WxHomework final {
 public:
  static constexpr char const* service_full_name() {
    return "wxhomework.WxHomework";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status doLogin(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::wxhomework::UserLoginResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::wxhomework::UserLoginResponse>> AsyncdoLogin(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::wxhomework::UserLoginResponse>>(AsyncdoLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::wxhomework::UserLoginResponse>> PrepareAsyncdoLogin(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::wxhomework::UserLoginResponse>>(PrepareAsyncdoLoginRaw(context, request, cq));
    }
    virtual ::grpc::Status doRegister(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::wxhomework::UserRegisterResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::wxhomework::UserRegisterResponse>> AsyncdoRegister(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::wxhomework::UserRegisterResponse>>(AsyncdoRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::wxhomework::UserRegisterResponse>> PrepareAsyncdoRegister(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::wxhomework::UserRegisterResponse>>(PrepareAsyncdoRegisterRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void doLogin(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserLoginResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void doLogin(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::wxhomework::UserLoginResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void doLogin(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserLoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void doLogin(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::wxhomework::UserLoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void doRegister(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserRegisterResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void doRegister(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::wxhomework::UserRegisterResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void doRegister(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserRegisterResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void doRegister(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::wxhomework::UserRegisterResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::wxhomework::UserLoginResponse>* AsyncdoLoginRaw(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::wxhomework::UserLoginResponse>* PrepareAsyncdoLoginRaw(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::wxhomework::UserRegisterResponse>* AsyncdoRegisterRaw(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::wxhomework::UserRegisterResponse>* PrepareAsyncdoRegisterRaw(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status doLogin(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::wxhomework::UserLoginResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::wxhomework::UserLoginResponse>> AsyncdoLogin(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::wxhomework::UserLoginResponse>>(AsyncdoLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::wxhomework::UserLoginResponse>> PrepareAsyncdoLogin(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::wxhomework::UserLoginResponse>>(PrepareAsyncdoLoginRaw(context, request, cq));
    }
    ::grpc::Status doRegister(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::wxhomework::UserRegisterResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::wxhomework::UserRegisterResponse>> AsyncdoRegister(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::wxhomework::UserRegisterResponse>>(AsyncdoRegisterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::wxhomework::UserRegisterResponse>> PrepareAsyncdoRegister(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::wxhomework::UserRegisterResponse>>(PrepareAsyncdoRegisterRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void doLogin(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserLoginResponse* response, std::function<void(::grpc::Status)>) override;
      void doLogin(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::wxhomework::UserLoginResponse* response, std::function<void(::grpc::Status)>) override;
      void doLogin(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserLoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void doLogin(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::wxhomework::UserLoginResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void doRegister(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserRegisterResponse* response, std::function<void(::grpc::Status)>) override;
      void doRegister(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::wxhomework::UserRegisterResponse* response, std::function<void(::grpc::Status)>) override;
      void doRegister(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserRegisterResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void doRegister(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::wxhomework::UserRegisterResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::wxhomework::UserLoginResponse>* AsyncdoLoginRaw(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::wxhomework::UserLoginResponse>* PrepareAsyncdoLoginRaw(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::wxhomework::UserRegisterResponse>* AsyncdoRegisterRaw(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::wxhomework::UserRegisterResponse>* PrepareAsyncdoRegisterRaw(::grpc::ClientContext* context, const ::wxhomework::UserInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_doLogin_;
    const ::grpc::internal::RpcMethod rpcmethod_doRegister_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status doLogin(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserLoginResponse* response);
    virtual ::grpc::Status doRegister(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserRegisterResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_doLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_doLogin() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_doLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doLogin(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserLoginResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdoLogin(::grpc::ServerContext* context, ::wxhomework::UserInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::wxhomework::UserLoginResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_doRegister : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_doRegister() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_doRegister() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doRegister(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserRegisterResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdoRegister(::grpc::ServerContext* context, ::wxhomework::UserInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::wxhomework::UserRegisterResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_doLogin<WithAsyncMethod_doRegister<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_doLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_doLogin() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::wxhomework::UserInfoRequest, ::wxhomework::UserLoginResponse>(
          [this](::grpc::ServerContext* context,
                 const ::wxhomework::UserInfoRequest* request,
                 ::wxhomework::UserLoginResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->doLogin(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_doLogin(
        ::grpc::experimental::MessageAllocator< ::wxhomework::UserInfoRequest, ::wxhomework::UserLoginResponse>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::wxhomework::UserInfoRequest, ::wxhomework::UserLoginResponse>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_doLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doLogin(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserLoginResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void doLogin(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserLoginResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_doRegister : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_doRegister() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::wxhomework::UserInfoRequest, ::wxhomework::UserRegisterResponse>(
          [this](::grpc::ServerContext* context,
                 const ::wxhomework::UserInfoRequest* request,
                 ::wxhomework::UserRegisterResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->doRegister(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_doRegister(
        ::grpc::experimental::MessageAllocator< ::wxhomework::UserInfoRequest, ::wxhomework::UserRegisterResponse>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::wxhomework::UserInfoRequest, ::wxhomework::UserRegisterResponse>*>(
          ::grpc::Service::experimental().GetHandler(1))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_doRegister() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doRegister(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserRegisterResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void doRegister(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserRegisterResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_doLogin<ExperimentalWithCallbackMethod_doRegister<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_doLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_doLogin() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_doLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doLogin(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserLoginResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_doRegister : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_doRegister() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_doRegister() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doRegister(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserRegisterResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_doLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_doLogin() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_doLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doLogin(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserLoginResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdoLogin(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_doRegister : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_doRegister() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_doRegister() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doRegister(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserRegisterResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdoRegister(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_doLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_doLogin() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->doLogin(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_doLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doLogin(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserLoginResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void doLogin(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_doRegister : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_doRegister() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->doRegister(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_doRegister() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doRegister(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserRegisterResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void doRegister(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_doLogin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_doLogin() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::wxhomework::UserInfoRequest, ::wxhomework::UserLoginResponse>(std::bind(&WithStreamedUnaryMethod_doLogin<BaseClass>::StreameddoLogin, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_doLogin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status doLogin(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserLoginResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreameddoLogin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::wxhomework::UserInfoRequest,::wxhomework::UserLoginResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_doRegister : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_doRegister() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::wxhomework::UserInfoRequest, ::wxhomework::UserRegisterResponse>(std::bind(&WithStreamedUnaryMethod_doRegister<BaseClass>::StreameddoRegister, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_doRegister() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status doRegister(::grpc::ServerContext* context, const ::wxhomework::UserInfoRequest* request, ::wxhomework::UserRegisterResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreameddoRegister(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::wxhomework::UserInfoRequest,::wxhomework::UserRegisterResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_doLogin<WithStreamedUnaryMethod_doRegister<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_doLogin<WithStreamedUnaryMethod_doRegister<Service > > StreamedService;
};

}  // namespace wxhomework


#endif  // GRPC_src_2fmain_2fproto_2fwxhomework_2eproto__INCLUDED
